import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Users,ChefHat,Package,Warehouse,Scissors,Factory,Settings,LogOut,Save,Plus} from 'lucide-react';
import './styles.css';
import Workspace from './Workspace';
import MaterialsStock from './MaterialsStock';
import UserManagement from './UserManagement';
import Production from './Production';
import CuttingOptimizer from './CuttingOptimizer';
import {supabase} from './supabase';

const menu=[['Dashboard',LayoutDashboard],['Clients',Users],['Kitchens',ChefHat],['Materials',Package],['Stock',Warehouse],['Cutting Optimizer',Scissors],['Production',Factory],['Settings',Settings]];
function App(){const [session,setSession]=useState(null),[company,setCompany]=useState(null),[permissions,setPermissions]=useState(new Set()),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let mounted=true;async function init(){const {data}=await supabase.auth.getSession();if(!mounted)return;setSession(data.session);if(data.session){await loadCompany();await loadPermissions()}setLoading(false)}init();const {data:{subscription}}=supabase.auth.onAuthStateChange(async(_event,next)=>{setSession(next);if(next){await loadCompany();await loadPermissions()}else{setCompany(null);setPermissions(new Set())}});return()=>{mounted=false;subscription.unsubscribe()}},[]);async function loadCompany(){try{const {data:{user}}=await supabase.auth.getUser();if(!user){setCompany(null);return}const {data,error}=await supabase.from('company_members').select('company_id,companies(*)').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();if(error)throw error;setCompany(data?.companies||false)}catch(e){setError(e.message)}}async function loadPermissions(){const {data,error}=await supabase.rpc('get_my_company_permissions');if(error){setError(error.message);return}setPermissions(new Set((data||[]).map(x=>x.permission_code)))}async function signOut(){await supabase.auth.signOut()}if(loading)return <div className="auth-shell"><div className="auth-card"><h1>Alum KitchenKit</h1><p>Chargement...</p></div></div>;if(!session)return <AuthScreen/>;if(company===false)return <CompanySetup onCreated={loadCompany} userEmail={session.user.email||''}/>;if(!company)return <div className="auth-shell"><div className="auth-card"><h1>Alum KitchenKit</h1><p>{error||'Chargement de votre entreprise...'}</p></div></div>;return <AppShell company={company} permissions={permissions} onCompanyUpdated={setCompany} onSignOut={signOut}/>}

function AuthScreen(){const [mode,setMode]=useState('login'),[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');async function submit(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{if(mode==='login'){const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error}else{if(!name.trim())throw new Error('Le nom complet est requis.');if(password!==confirm)throw new Error('Les mots de passe ne correspondent pas.');if(password.length<8)throw new Error('Le mot de passe doit contenir au moins 8 caractères.');const {data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:name.trim(),phone:phone.trim()}}});if(error)throw error;setMessage(data.session?'Compte créé.':'Compte créé. Vérifiez votre email puis connectez-vous.');if(data.session)setMode('login')}}catch(e){setError(e.message)}finally{setBusy(false)}}return <div className="auth-shell"><div className="auth-card"><div className="brand auth-brand"><div className="logo">AK</div><div><strong>Alum KitchenKit</strong><small>Kitchen manufacturing</small></div></div><h1>{mode==='login'?'Connexion':'Créer un compte'}</h1>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}{mode==='signup'&&<><label>Nom complet<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Téléphone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label></>}<form onSubmit={submit}><label>Email professionnel<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mot de passe<input type="password" required minLength="8" value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode==='signup'&&<label>Confirmer le mot de passe<input type="password" required minLength="8" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}<button className="primary" disabled={busy}>{busy?'...':mode==='login'?'Se connecter':'Créer le compte'}</button></form><button className="link-button" onClick={()=>{setMode(mode==='login'?'signup':'login');setError('');setMessage('')}}>{mode==='login'?'Créer un nouveau compte':'J’ai déjà un compte'}</button></div></div>}

function CompanySetup({onCreated,userEmail}){const [form,setForm]=useState({name:'',phone:'',email:userEmail,address:'',currency:'DZD'}),[busy,setBusy]=useState(false),[error,setError]=useState('');const set=(k,v)=>setForm(f=>({...f,[k]:v}));async function submit(e){e.preventDefault();setBusy(true);setError('');try{const {error}=await supabase.rpc('create_company_for_current_user',{p_name:form.name,p_phone:form.phone||null,p_email:form.email||null,p_address:form.address||null,p_currency:form.currency});if(error)throw error;await onCreated()}catch(e){setError(e.message)}finally{setBusy(false)}}return <div className="auth-shell"><div className="auth-card wide"><h1>Créer votre entreprise</h1>{error&&<div className="error">{error}</div>}<form onSubmit={submit}><label>Nom de l’entreprise *<input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Téléphone<input value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Email de l’entreprise<input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Adresse<input value={form.address} onChange={e=>set('address',e.target.value)}/></label><label>Devise<select value={form.currency} onChange={e=>set('currency',e.target.value)}><option value="DZD">DZD</option><option value="EUR">EUR</option><option value="USD">USD</option></select></label><button className="primary" disabled={busy}>Créer mon espace entreprise</button></form></div></div>}

function AppShell({company,permissions,onCompanyUpdated,onSignOut}){const [page,setPage]=useState('Dashboard');const [settingsTab,setSettingsTab]=useState('company');const [selectedKitchen,setSelectedKitchen]=useState(null);const canUsers=permissions.has('users.view')||permissions.has('users.manage');const canCompany=permissions.has('company.manage');return <div className="app"><aside><div className="brand"><div className="logo">AK</div><div><strong>Alum KitchenKit</strong><small>{company.name}</small></div></div><nav>{menu.map(([name,Icon])=>{if(name==='Clients'&&!permissions.has('customers.view'))return null;if(name==='Materials'&&!permissions.has('materials.view'))return null;if(name==='Stock'&&!permissions.has('stock.view'))return null;if(name==='Cutting Optimizer'&&!permissions.has('cutting.view'))return null;if(name==='Production'&&!permissions.has('production.view'))return null;if(name==='Settings'&&!canCompany&&!canUsers)return null;return <button className={page===name?'active':''} onClick={()=>setPage(name)} key={name}><Icon size={18}/>{name}</button>})}</nav><button className="logout" onClick={onSignOut}><LogOut size={17}/> Déconnexion</button></aside><main><header><div><h1>{page}</h1><p>Gestion de fabrication de cuisines aluminium</p></div></header>{page==='Dashboard'?<Dashboard company={company}/>:page==='Kitchens'?<Workspace onKitchenSelected={setSelectedKitchen}/>:page==='Materials'||page==='Stock'?<MaterialsStock/>:page==='Production'?<ProductionPage selectedKitchen={selectedKitchen} onSelect={setSelectedKitchen}/>:page==='Cutting Optimizer'?<CuttingPage/>:page==='Settings'?<SettingsPage company={company} canCompany={canCompany} canUsers={canUsers} tab={settingsTab} setTab={setSettingsTab} onCompanyUpdated={onCompanyUpdated}/>:<section className="panel empty">Module non disponible.</section>}</main></div>}

function Dashboard({company}){return <><section className="cards"><Card title="Entreprise" value={company.name}/><Card title="Devise" value={company.currency||'DZD'}/><Card title="Statut" value="Connecté"/></section><section className="panel"><h2>Alum KitchenKit</h2><p>Base de données Supabase connectée. Les modules principaux utilisent maintenant les données réelles.</p></section></>}
function Card({title,value}){return <div className="card"><span>{title}</span><strong>{value}</strong></div>}
function ProductionPage({selectedKitchen,onSelect}){const [kitchens,setKitchens]=useState([]);useEffect(()=>{load()},[]);async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:m}=await supabase.from('company_members').select('company_id').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();if(!m)return;const {data}=await supabase.from('kitchens').select('*').eq('company_id',m.company_id).order('created_at',{ascending:false});setKitchens(data||[]);if(!selectedKitchen&&data?.[0])onSelect(data[0])}return <><section className="panel"><div className="panelhead"><div><h2>Ordre de fabrication</h2><p>Choisissez une cuisine.</p></div></div><div className="list">{kitchens.map(k=><button className={selectedKitchen?.id===k.id?'selected':''} key={k.id} onClick={()=>onSelect(k)}>{k.reference} — {k.name}</button>)}</div>{!kitchens.length&&<p>Aucune cuisine. Créez-en une dans Kitchens.</p>}</section>{selectedKitchen&&<Production kitchen={selectedKitchen}/>}</>}
function CuttingPage(){const [order,setOrder]=useState(null);useEffect(()=>{load()},[]);async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:m}=await supabase.from('company_members').select('company_id').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();if(!m)return;const {data}=await supabase.from('production_orders').select('*').eq('company_id',m.company_id).order('created_at',{ascending:false}).limit(1).maybeSingle();setOrder(data)}return <CuttingOptimizer productionOrderId={order?.id}/>}
function SettingsPage({company,canCompany,canUsers,tab,setTab,onCompanyUpdated}){return <><div className="tabs">{canCompany&&<button className={tab==='company'?'active':''} onClick={()=>setTab('company')}>Entreprise</button>}{canUsers&&<button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>Utilisateurs</button>}</div>{tab==='company'&&canCompany?<CompanySettings company={company} onSaved={onCompanyUpdated}/>:tab==='users'&&canUsers?<UserManagement/>:<section className="panel empty">Accès limité.</section>}</>}
function CompanySettings({company,onSaved}){const [form,setForm]=useState({name:company.name||'',phone:company.phone||'',email:company.email||'',address:company.address||'',logo_url:company.logo_url||'',currency:company.currency||'DZD'}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);const set=(k,v)=>setForm(f=>({...f,[k]:v}));async function save(e){e.preventDefault();setBusy(true);setError('');try{const {data,error}=await supabase.rpc('update_company_for_current_user',{p_name:form.name,p_phone:form.phone||null,p_email:form.email||null,p_address:form.address||null,p_logo_url:form.logo_url||null,p_currency:form.currency});if(error)throw error;onSaved(data);setSaved(true)}catch(e){setError(e.message)}finally{setBusy(false)}}return <section className="panel"><h2>Profil de l’entreprise</h2>{error&&<div className="error">{error}</div>}{saved&&<div className="success">Informations enregistrées.</div>}<form className="material-form" onSubmit={save}><label>Nom *<input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Téléphone<input value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Adresse<input value={form.address} onChange={e=>set('address',e.target.value)}/></label><label>Devise<select value={form.currency} onChange={e=>set('currency',e.target.value)}><option>DZD</option><option>EUR</option><option>USD</option></select></label><button className="primary" disabled={busy}><Save size={17}/>Enregistrer</button></form></section>}
createRoot(document.getElementById('root')).render(<App/>);