import React,{useEffect,useState} from 'react';
import {supabase} from './supabase';
const empty={name:'',material_type:'profile',purchase_unit:'piece',purchase_length_m:'',sheet_length_m:'',sheet_width_m:'',unit_price:'',stock_quantity:'0',low_stock_threshold:'0'};
export default function MaterialsStock(){
 const [materials,setMaterials]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[companyId,setCompanyId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{load()},[]);
 async function load(){try{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:m,error:e}=await supabase.from('company_members').select('company_id').eq('user_id',user.id).limit(1).single();if(e)throw e;setCompanyId(m.company_id);const {data,error}=await supabase.from('materials').select('*').eq('company_id',m.company_id).order('name');if(error)throw error;setMaterials(data||[])}catch(e){setError(e.message)}}
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const payload={...form,company_id:companyId,purchase_length_m:num(form.purchase_length_m),sheet_length_m:num(form.sheet_length_m),sheet_width_m:num(form.sheet_width_m),unit_price:num(form.unit_price),stock_quantity:num(form.stock_quantity),low_stock_threshold:num(form.low_stock_threshold)};const q=editing?supabase.from('materials').update(payload).eq('id',editing).select().single():supabase.from('materials').insert(payload).select().single();const {data,error}=await q;if(error)throw error;setMaterials(xs=>editing?xs.map(x=>x.id===editing?data:x):[...xs,data].sort((a,b)=>a.name.localeCompare(b.name)));setForm(empty);setEditing(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 function edit(m){setEditing(m.id);setForm({...empty,...m})}
 async function stock(m,type){const value=window.prompt(type==='in'?'Quantité à ajouter':'Quantité à sortir','1');if(value===null)return;setBusy(true);try{const {data,error}=await supabase.rpc('adjust_material_stock',{p_material_id:m.id,p_quantity:Number(value),p_movement_type:type,p_notes:'Manual stock operation'});if(error)throw error;setMaterials(xs=>xs.map(x=>x.id===m.id?{...x,stock_quantity:data}:x))}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="materials-page"><div className="panel"><div className="panelhead"><div><h2>Materials & Stock</h2><p>Prix, dimensions et stock de chaque matière.</p></div></div>{error&&<div className="error">{error}</div>}<form className="material-form" onSubmit={save}><label>Nom<input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="1 Départ"/></label><label>Type<select value={form.material_type} onChange={e=>set('material_type',e.target.value)}><option value="profile">Profile</option><option value="sheet">Résine / Aluco</option><option value="accessory">Accessory</option></select></label><label>Unité d'achat<input value={form.purchase_unit} onChange={e=>set('purchase_unit',e.target.value)} placeholder="piece"/></label>{form.material_type==='profile'&&<label>Longueur unité (m)<input type="number" step="0.001" value={form.purchase_length_m} onChange={e=>set('purchase_length_m',e.target.value)}/></label>}{form.material_type==='sheet'&&<><label>Longueur plaque (m)<input type="number" step="0.001" value={form.sheet_length_m} onChange={e=>set('sheet_length_m',e.target.value)}/></label><label>Largeur plaque (m)<input type="number" step="0.001" value={form.sheet_width_m} onChange={e=>set('sheet_width_m',e.target.value)}/></label></>}<label>Prix achat<input type="number" step="0.01" value={form.unit_price} onChange={e=>set('unit_price',e.target.value)}/></label><label>Stock actuel<input type="number" step="0.001" value={form.stock_quantity} onChange={e=>set('stock_quantity',e.target.value)}/></label><label>Seuil alerte<input type="number" step="0.001" value={form.low_stock_threshold} onChange={e=>set('low_stock_threshold',e.target.value)}/></label><div className="form-actions"><button className="primary" disabled={busy}>{editing?'Enregistrer':'Ajouter'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Annuler</button>}</div></form></div><div className="panel"><h3>Catalogue</h3><div className="material-table"><div className="material-head"><span>Material</span><span>Type</span><span>Dimension</span><span>Prix</span><span>Stock</span><span>Actions</span></div>{materials.map(m=><div className="material-row" key={m.id}><b>{m.name}</b><span>{m.material_type}</span><span>{m.material_type==='profile'?`${m.purchase_length_m||0} m`:`${m.sheet_length_m||0} × ${m.sheet_width_m||0} m`}</span><span>{Number(m.unit_price||0).toLocaleString('fr-DZ')} DA</span><span className={Number(m.stock_quantity)<=Number(m.low_stock_threshold)?'stock-low':'stock-ok'}>{m.stock_quantity} {m.purchase_unit}</span><div><button onClick={()=>edit(m)}>Modifier</button><button onClick={()=>stock(m,'in')}>+ Stock</button><button onClick={()=>stock(m,'out')}>− Stock</button></div></div>)}</div></div></section>}
function num(v){return v===''||v==null?null:Number(v)}
