import React,{useEffect,useState} from 'react';
import {supabase} from './supabase';

const roles=[['admin','Admin'],['commercial','Commercial'],['atelier','Atelier'],['accountant','Comptable']];

export default function UserManagement(){
 const [users,setUsers]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [form,setForm]=useState({full_name:'',position:'',email:'',password:'',role:'atelier'});
 async function load(){setLoading(true);setError('');try{const {data,error}=await supabase.rpc('admin_list_company_users');if(error)throw error;setUsers(data||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function add(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{if(form.password.length<8)throw new Error('Le mot de passe doit contenir au moins 8 caractères.');const {data:{session}}=await supabase.auth.getSession();const {data,error}=await supabase.functions.invoke('admin-manage-users',{body:{action:'create',full_name:form.full_name,position:form.position,email:form.email,password:form.password,role:form.role},headers:{Authorization:`Bearer ${session.access_token}`}});if(error)throw error;if(data?.error)throw new Error(data.error);setForm({full_name:'',position:'',email:'',password:'',role:'atelier'});setMessage('Utilisateur créé avec succès.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function toggle(u){setBusy(true);setError('');try{const {data:{session}}=await supabase.auth.getSession();const {data,error}=await supabase.functions.invoke('admin-manage-users',{body:{action:'set_status',user_id:u.user_id,active:!u.active},headers:{Authorization:`Bearer ${session.access_token}`}});if(error)throw error;if(data?.error)throw new Error(data.error);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function changeRole(u,role){setBusy(true);setError('');try{const {data:{session}}=await supabase.auth.getSession();const {data,error}=await supabase.functions.invoke('admin-manage-users',{body:{action:'set_role',user_id:u.user_id,role},headers:{Authorization:`Bearer ${session.access_token}`}});if(error)throw error;if(data?.error)throw new Error(data.error);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel"><div className="panelhead"><div><h2>Utilisateurs de l’entreprise</h2><p>Ajoutez les membres de votre équipe et attribuez leurs rôles.</p></div></div>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<form className="material-form" onSubmit={add}><label>Nom complet *<input required value={form.full_name} onChange={e=>set('full_name',e.target.value)} /></label><label>Poste / Fonction<input value={form.position} onChange={e=>set('position',e.target.value)} placeholder="Ex. Responsable atelier" /></label><label>Email *<input required type="email" value={form.email} onChange={e=>set('email',e.target.value)} /></label><label>Mot de passe initial *<input required type="password" minLength="8" value={form.password} onChange={e=>set('password',e.target.value)} /></label><label>Rôle<select value={form.role} onChange={e=>set('role',e.target.value)}>{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="form-actions"><button className="primary" disabled={busy}>{busy?'...':'Ajouter l’utilisateur'}</button></div></form><div className="table-wrap"><table><thead><tr><th>Nom</th><th>Poste</th><th>Email</th><th>Rôle</th><th>Statut</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan="6">Chargement...</td></tr>:users.map(u=><tr key={u.user_id}><td>{u.full_name||'—'}</td><td>{u.position||'—'}</td><td>{u.email||'—'}</td><td><select value={u.role} disabled={busy} onChange={e=>changeRole(u,e.target.value)}>{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td>{u.active?'Actif':'Désactivé'}</td><td><button className="secondary" disabled={busy} onClick={()=>toggle(u)}>{u.active?'Désactiver':'Activer'}</button></td></tr>)}</tbody></table></div></section>
}