import React,{useEffect,useState} from 'react';
import {supabase} from './supabase';
const roles=[['admin','Admin'],['manager','Manager'],['worker','Worker'],['viewer','Viewer'],['commercial','Commercial'],['atelier','Atelier'],['accountant','Comptable']];
const permissions={admin:'Accès complet',manager:'Clients, cuisines, matériaux, stock, production et impression',worker:'Kitchens, boîtes, cutting plans, production et impression',viewer:'Consultation uniquement',commercial:'Clients, cuisines et consultation des coûts',atelier:'Boîtes, cutting plans, production et stock atelier',accountant:'Coûts, achats, stock et rapports'};
export default function UserManagement(){
 const [users,setUsers]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [form,setForm]=useState({full_name:'',position:'',email:'',password:'',role:'worker'});
 async function call(body){const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Session administrateur expirée. Veuillez vous reconnecter.');const {data,error}=await supabase.functions.invoke('admin-manage-users-v2',{body,headers:{Authorization:`Bearer ${session.access_token}`}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
 async function load(){setLoading(true);setError('');try{const data=await call({action:'list'});setUsers(Array.isArray(data)?data:[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function add(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{if(form.password.length<8)throw new Error('Le mot de passe doit contenir au moins 8 caractères.');await call({action:'create',full_name:form.full_name.trim(),position:form.position.trim(),email:form.email.trim(),password:form.password,role:form.role});setForm({full_name:'',position:'',email:'',password:'',role:'worker'});setMessage('Utilisateur créé.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function toggle(u){setBusy(true);setError('');try{await call({action:'set_status',user_id:u.user_id,active:u.status!=='active'});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function changeRole(u,role){setBusy(true);setError('');try{await call({action:'set_role',user_id:u.user_id,role});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel"><div className="panelhead"><div><h2>Utilisateurs &amp; permissions</h2><p>Gérez les membres de l’entreprise et leurs accès.</p></div></div>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<form className="material-form" onSubmit={add}><label>Nom complet *<input required value={form.full_name} onChange={e=>set('full_name',e.target.value)} /></label><label>Poste / Fonction *<input required value={form.position} onChange={e=>set('position',e.target.value)} placeholder="Ex. Responsable atelier" /></label><label>Email *<input required type="email" value={form.email} onChange={e=>set('email',e.target.value)} /></label><label>Mot de passe initial *<input required type="password" minLength="8" value={form.password} onChange={e=>set('password',e.target.value)} /></label><label>Rôle<select value={form.role} onChange={e=>set('role',e.target.value)}>{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="form-actions"><button className="primary" disabled={busy}>{busy?'...':'Ajouter l’utilisateur'}</button></div></form><div className="table-wrap"><table><thead><tr><th>Nom</th><th>Poste</th><th>Email</th><th>Rôle</th><th>Statut</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan="6">Chargement...</td></tr>:users.map(u=><tr key={u.user_id}><td>{u.full_name||'—'}</td><td>{u.job_title||'—'}</td><td>{u.email||'—'}</td><td><select value={u.role} disabled={busy} onChange={e=>changeRole(u,e.target.value)}>{roles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td>{u.status==='active'?'Actif':'Désactivé'}</td><td><button type="button" className="secondary" disabled={busy} onClick={()=>toggle(u)}>{u.status==='active'?'Désactiver':'Activer'}</button></td></tr>)}</tbody></table></div><div className="panel" style={{marginTop:20}}><div className="panelhead"><div><h3>Permissions par rôle</h3><p>Les droits sont appliqués au niveau de l’application et de la base de données.</p></div></div><div className="table-wrap"><table><thead><tr><th>Rôle</th><th>Accès</th></tr></thead><tbody>{roles.map(([v,l])=><tr key={v}><td><strong>{l}</strong></td><td>{permissions[v]}</td></tr>)}</tbody></table></div></div></section>
}